### ISSUE TITLE
better debugging of exceptions in set fns

### ISSUE THREAD

**Issue by limbolabs** [ReadyForZero/babbage#10]
sometimes excpetions in "sets" functions can be very hard to debug. would be really helpful to try/catch those for example

**Comment by bwo** [comment]
I take it pos? on nil was one of these?

**Comment by ithayer** [comment]
yep in this case, but this has happened before. it's not a babbage issue
per se, but it would be really helpful

**Comment by limbolabs** [comment]
is this one easy too? this would be useful

**Comment by bwo** [comment]
what would be more helpful here? it seems like a place where resumable exns might be helpful (so that you could say "log this and skip it" or "stop everything" or whatever), but I'm not sure if that would be the sort of thing you're after

**Comment by ithayer** [comment]
anyhthing would be fine,  "stop everything" seems like it would be most
correct

**Comment by bwo** [comment]
stop everything is current behavior, isn't it? since it just throws an exception.

**Comment by ithayer** [comment]
Ok i forgot. Ok to close

ignacio
